version: '3.8'

services:
  full:
    build:
      context: .
      dockerfile: Dockerfile
      target: full
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
      - USE_LIGHTRAG=true
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    volumes:
      - .:/app
    command: ["python", "app.py"]
    ports:
      - "7860:7860"
